#!/usr/bin/env bash

sudo pacman -Syu --noconfirm linux-firmware mesa vulkan-radeon sof-firmware pipewire pipewire-alsa pipewire-pulse networkmanager power-profiles-daemon xf86-video-amdgpu amd-ucode && sudo systemctl enable --now NetworkManager power-profiles-daemon
