set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

unbind C-b
set-option -g prefix C-g
bind-key C-g send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

set -g base-index 1
set -g renumber-windows on
set-window-option -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# pane navigation
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# window navigation
bind-key -n M-1 select-window -t :1
bind-key -n M-2 select-window -t :2
bind-key -n M-3 select-window -t :3
bind-key -n M-4 select-window -t :4
bind-key -n M-5 select-window -t :5
bind-key -n M-6 select-window -t :6
bind-key -n M-7 select-window -t :7
bind-key -n M-8 select-window -t :8
bind-key -n M-9 select-window -t :9

bind -r n next-window
bind -r p previous-window
bind w choose-window

#bind -r D new-window -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/.dotfiles/personal/todo.md"

bind-key -r f display-popup -E -w 80% -h 80% "~/.local/bin/pmux"

bind-key -r m display-popup -E -w 80% -h 80% "~/.local/bin/pmux-run"
bind-key -r M display-popup -E -w 80% -h 80% "~/.local/bin/pmux-run --multi"

bind-key -r / display-popup -E -w 80% -h 80% "~/.local/bin/pmux-cheat"

# styling base
set -g status-left-length 20

# loom theme
source-file ~/.local/state/loom/generated/tmux-theme.conf
