# Enable colors and change prompt:
setopt autocd		# Automatically cd into typed directory.
stty stop undef		# Disable ctrl-s to freeze terminal.
setopt interactive_comments

# History in cache directory:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.cache/zsh/history

# Load alias and shortcuts
source ~/.config/shell/aliases.zsh
source ~/.config/shell/shortcuts.zsh

# vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

bindkey -s '^f' "tmux-sessionizer\n"

export PATH=/home/veasman/.local/bin:$PATH

# Lua LSP
alias luamake=/home/veasman/.local/bin/lua-language-server/3rd/luamake/luamake
