general {
    gaps_in = 20
    gaps_out = 16
    border_size = 3
    col.active_border = rgba(f29fc2ff)
    col.inactive_border = rgba(e7bfd1ff)
}

decoration {
    rounding = 14
    active_opacity = 1.0
    inactive_opacity = 0.95

    shadow {
        enabled = true
        range = 20
        render_power = 2
        color = rgba(00000055)
    }

    blur {
        enabled = false
    }
}

animations {
    enabled = no
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    middle_click_paste = false
}
